### ISSUE TITLE
Lean Body Mass formula

### ISSUE THREAD

**Issue by dmhardin102** [Fitomics/nutritioncalc#1]
@drhaun what formula do we want to use for lean body mass and protein calculation?

**Comment by dmhardin102** [comment]
fat-free mass * range adjusted to 1, 1.2, 1.4, 1.6, 1.8, 2.0

**Comment by drhaun** [comment]
Addressed!

Starting with 1.2, 1.4, 1.6, 1.8, 2.0 g/kg of ffm/day

**Comment by dmhardin102** [comment]
fixed

**Comment by drhaun** [comment]
@dmhardin102 

While we were ping ponging a few topics on this, I think my brain was still getting pulled to g/lb and g/kg body mass per day coefficients instead of g/kg of FFM.

Let’s use 5 options, considering anticipated avg user of this tool, let’s use these coefficients:

2.0, 2.2, 2.4, 2.6, 2.8

It might seem pedantic but these are more appropriate for anticipated users and with constraints of this foundational calculator in mind using a multiplier of kg FFM to set targets.

**Comment by drhaun** [comment]
Sorry for any hassle, but that should get us onto the  next step. Should be quick fix, thanks!

**Comment by dmhardin102** [comment]
no problem. adjusted and pushed to the live site.

**Comment by drhaun** [comment]
<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/92a5d326-22a8-4e38-bd77-9a9aa59408ad" />@dmhardin102 looks like the calculator is still multiplying by kg body mass, not kg fat-free mass.

**Comment by drhaun** [comment]
@dmhardin102 actually, I see what it is. Fat mass and fat-free mass are showing in lbs, not kg. So, the fat mass and fat-free mass values could be shown in kg instead of lbs and then we should be good to go.

<img width="1133" alt="Image" src="https://github.com/user-attachments/assets/1b96a3dc-111f-40a2-8746-d37cdd2cb7a2" />

**Comment by dmhardin102** [comment]
@drhaun to clarify, is there a value on the bottom that needs a new calculation? Or, is it just that some values are shown in lbs up top, and the kg calculation happens behind the scenes, but we still have correct value numeric values in all boxes?

**Comment by drhaun** [comment]
The calculated protein amount is way off because fat-free mass in pounds is being used instead of fat-free mass in kilograms. After body fat percentage is entered, the fat mass and fat-free mass calculations can be calculated in kilograms not pounds and that should fix it.

**Comment by dmhardin102** [comment]
@drhaun ohhh, I see. I just fixed it to convert FFM from lbs to kg before multiplying by the protein factor. Let me know if that fixes it. You may have to delete out all values from the calculator and refresh if the old equations are leftover in your browser cache.

**Comment by drhaun** [comment]
Appears to be working now, nice!

Is the next stage building off of the Figma design and hosting through a fitomics.org url as a multi-step web-app?

Anything I can do to help expedite that?

@dmhardin102

**Comment by dmhardin102** [comment]
@drhaun yea, next step is a complete rebuild of the tech with a more modern, scalable architecture, but thankfully much of the design is in place or at least in process.

**Comment by drhaun** [comment]
@dmhardin102 what's a general outline (in steps) of a complete rebuild leveraging the Figma mockups?

**Comment by dmhardin102** [comment]
@drhaun would be something similar to the cronometer dashboard. build backend, build database, drop in figma components. push to something like pythonanywhere or possibly host more directly on a google virtual machine. app build should be quicker than crono app, but deployment and hosting will be a little more involved for the frontend functionality. would also plan to build in email capture and pdf generation if doing a whole rebuild. Can open up an item on monday to detail further and keep this public thread clean.
